package Messaging;

public enum MessageType {
    REQUEST_CERT,
    CERT_ISSUED,
    VERIFY_CERT,
    REQUEST_REGISTRATION,
    NOTIFY_TL,
    NOTIFY_TL_TA,
    NOTIFY_TL_CA,
    REQUEST_ATTESTATION,
    ATTESTATION_VERIFIED,
    ATTESTATION_ISSUED,
    REVOKE_ATTESTATION,
    REQUEST_PRESENTATION,
    PRESENT_PRESENTATION,
    REQUEST_TL_CERTIFICATE,
    SEND_PUBLIC_KEY,
    REQUEST_PUBLIC_KEY,
    RESPONSE_PUBLIC_KEY,
    START,
    ERROR
}
