package Messaging;

public enum MessageType {
    REQUEST_CERT,
    CERT_ISSUED,
    NOTIFY_TL,
    REQUEST_ATTESTATION,
    ATTESTATION_ISSUED,
    REQUEST_PRESENTATION,
    PRESENT_PRESENTATION,
    REQUEST_TL_CERTIFICATE,
    REQUEST_PUBLIC_KEY,
    RESPONSE_PUBLIC_KEY,
    START,
    ERROR
}
